# Pull PostgresSQL Image
version: '3.8'
services:
    db:
        # Lightweight PostgreSQL Image
        image: postgres:15-alpine
        restart: always
        # Environment variables for database configuration
        environment:
            POSTGRES_USER: harisrid
            POSTGRES_PASSWORD: harisrid
            POSTGRES_DB: harisrid_db
        # Expose the port for external access
        ports:
            # hostPort:containerPort mappings
            - "5432:5432"
        # Named volume mountained for data persistence
        volumes:
            - db_data:/var/lib/postgresql/data

# Named Volume for Data Persistence
volumes:
    db_data: # Define the named volume for data persistence
